prompts:
 base_system_prompt: |
    You are an AI assistant helping a user with their writing.
    You should always only modify the text and never engage in conversation with the user.
 fix_grammar_prompt: |
    Fix typographical and grammatical errors in the text.
 rephrase_prompt: |
    Revise the text to make it more clear and concise.
 one_word_prompt: "Fix the spelling of the word: "
 context_prompt: "The text and the tone should be appropriate for {}"
 postscript: "These were the instructions, what follows is the user message."
