services:
  # Main FastAPI application service
  web:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    depends_on:
      - redis
    env_file:
      - .env
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    # Map port 8000 on host to port 80 in container (for local development)
    ports:
      - "8000:80"
    networks:
      - steer

  # Redis for caching and message broker
  redis:
    image: "redis:alpine"
    networks:
      - steer

networks:
  # Internal network for backend services
  steer:
    driver: bridge
