version: '3.8'

services:
  web:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    depends_on:
      - redis
    env_file:
      - .env
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    networks:
      - steer

  nginx:
    image: nginx:1.21.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - steer
      - electron-updater


  redis:
    image: "redis:alpine"

networks:
  steer:
    driver: bridge
  electron-updater:
    name: electron-release-server_electron-updater
    external: true

