version: '3.8'

services:
  web:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    depends_on:
      - redis
    env_file:
      - .env
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379

  nginx:
    image: nginx:1.21.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web


  redis:
    image: "redis:alpine"
