version: '3.8'

services:
  web:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    env_file:
      - .env

  nginx:
    image: nginx:1.21.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web